import {
  Area, Bar, Candle, ClipPath, Curve, ErrorBar, Line, Point, Slice, Voronoi, Flyout,
  VictoryAnimation,
  VictoryArea,
  VictoryAxis,
  VictoryBar,
  VictoryCandlestick,
  VictoryChart,
  VictoryContainer,
  VictoryErrorBar,
  VictoryGroup,
  VictoryLine,
  VictoryLabel,
  VictoryPie,
  VictoryScatter,
  VictoryStack,
  VictoryTheme,
  VictoryTransition,
  VictorySharedEvents,
  VictoryTooltip,
  VictoryVoronoi,
  VictoryVoronoiTooltip
} from 'victory';

export {
  Area, Bar, Candle, ClipPath, Curve, ErrorBar, Line, Point, Slice, Voronoi, Flyout,
  VictoryAnimation,
  VictoryArea,
  VictoryAxis,
  VictoryBar,
  VictoryCandlestick,
  VictoryChart,
  VictoryContainer,
  VictoryErrorBar,
  VictoryGroup,
  VictoryLine,
  VictoryLabel,
  VictoryPie,
  VictoryScatter,
  VictoryStack,
  VictoryTheme,
  VictoryTransition,
  VictorySharedEvents,
  VictoryTooltip,
  VictoryVoronoi,
  VictoryVoronoiTooltip
};
